DefaultContentLanguage: en-us
author: Houwb
baseURL: https://houwb-blog.netlify.app/
copyright: Copyright © 2008–2021
disqusShortname: YOURSHORTNAME
enableInlineShortcodes: yes
footnoteReturnLinkContents: ^
googleAnalytics: UA-FAKE
hasCJKLanguage: yes
languageCode: en-us
theme: hugo-theme-tokiwa
title: Houwb blog
markup:
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    style: monokailight
params:
  bannerFont: fonts/exampleFont
  description: "迷茫但有追求的生信人\r\n"
  env: production
  favicon: img/favicon-32x32.png
  fuse: yes
  math: yes
  postDateFormat: 2006-1-2
  useChineseFonts: yes
menu:
  main:
    - identifier: post
      name: Posts
      url: /post/
      weight: 1
    - name: Tags
      url: /tags/
      weight: 2
    - name: Categories
      url: /categories/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 3
taxonomies:
  category: categories
  series: series
  tag: tags
social:
  github: https://github.com/houweibo-wm
outputs:
  home:
    - HTML
    - RSS
    - JSON